swagger: "2.0"
info:
  version: "0.0.1"
  title: API base system
# during dev, should point to your local machine
host: localhost:7100
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |
      For accessing the API a valid JWT token must be passed in all the queries in
      the 'Authorization' header.


consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:

  /accounts:
    x-swagger-router-controller: account_controller
    post:
      operationId: create
      description: "Create an account"
      tags:
        - API
      parameters:
        - in: body
          name: "CreateAccount"
          schema:
           $ref: "#/definitions/CreateAccount"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Response"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ErrorResponse"


  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  Response:
    type: object
    properties:
      message:
        type: string

  CreateAccount:
    required:
      - name
    properties:
      name:
        type: string
